services:
  mercado-pago-nodejs:
    container_name: mercado-pago
    dns:
      - 8.8.8.8
      - 8.8.4.4
    build:
      context: ./
      args:
        - PORT=${PORT}
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - MERCADO_PAGO_ACCESS_TOKEN=${MERCADO_PAGO_ACCESS_TOKEN}
      - MERCADO_PAGO_WEBHOOK_URL=${MERCADO_PAGO_WEBHOOK_URL}
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      - MERCADO_PAGO_WEBHOOK_SECRET=${MERCADO_PAGO_WEBHOOK_SECRET}
      - NGROK_STATIC_DOMAIN=${NGROK_STATIC_DOMAIN}
    ports:
      - "3030:${PORT}"
    restart: unless-stopped
    networks:
      - local-network

networks:
  local-network:
    driver: bridge